[package]
name = "repomng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.16", default-features = false, features = ["http1", "json"] }
clap = { version = "3.2.21", features = ["derive", "env"] }
eyre = "0.6.8"
git2 = "0.15.0"
hyper = "0.14.20"
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1.21.1", default-features = false, features = ["macros", "rt-multi-thread"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
